---
version: "2.1"
services:
    plex:
        image: lscr.io/linuxserver/plex:latest
        container_name: plex
        #network_mode: host
        environment:
          - PUID=1000
          - PGID=1000
          - TZ=Etc/UTC
          - VERSION=docker
          - PLEX_CLAIM="${PLEX_CLAIM}" # optional, good for 4 minutes to assign new installation to your account. Obtained from https://plex.tv/claim 
        ports:
          - "${PORT}:80"
        #labels:
        #   caddy: "${CADDY_URL_SUBDOMAIN}.${CADDY_URL_DOMAIN}"
        #   caddy.reverse_proxy: "{{upstreams 80}}"
        volumes:
          - plex-config:/config
          - /mnt/share/media/:/media
        restart: unless-stopped

    backup:
        image: mazzolino/restic
        hostname: docker
        environment:
            RUN_ON_STARTUP: "true"
            BACKUP_CRON: "0 30 3 * * *"
            S3_REGION: auto
            AWS_ACCESS_KEY_ID: "${S3_ACCESS_KEY_ID}"
            AWS_SECRET_ACCESS_KEY: "${S3_SECRET_ACCESS_KEY}"
            RESTIC_REPOSITORY: "s3:${S3_ENDPOINT}/${S3_BUCKET}/${S3_PREFIX}/files"
            RESTIC_PASSWORD: ${ENCRYPTION_PASSWORD}
            RESTIC_BACKUP_SOURCES: /data
            RESTIC_BACKUP_ARGS: >-
                --tag ${RESTIC_TAG}
                --verbose
            RESTIC_FORGET_ARGS: >-
                --keep-last 10 --keep-daily 7 --keep-weekly 2 --keep-monthly 12
            TZ: CET
        volumes:
            - plex-config:/data:ro

    prune:
        image: mazzolino/restic
        hostname: docker
        environment:
            RUN_ON_STARTUP: "true"
            PRUNE_CRON: "0 0 4 * * *"
            AWS_ACCESS_KEY_ID: "${S3_ACCESS_KEY_ID}"
            AWS_SECRET_ACCESS_KEY: "${S3_SECRET_ACCESS_KEY}"
            RESTIC_REPOSITORY: "s3:${S3_ENDPOINT}/${S3_BUCKET}/${S3_PREFIX}/files"
            RESTIC_PASSWORD: ${ENCRYPTION_PASSWORD}
            TZ: CET

    check:
        image: mazzolino/restic
        hostname: docker
        environment:
            RUN_ON_STARTUP: "false"
            CHECK_CRON: "0 15 5 * * *"
            RESTIC_CHECK_ARGS: >-
                --read-data-subset=10%
            AWS_ACCESS_KEY_ID: "${S3_ACCESS_KEY_ID}"
            AWS_SECRET_ACCESS_KEY: "${S3_SECRET_ACCESS_KEY}"
            RESTIC_REPOSITORY: "s3:${S3_ENDPOINT}/${S3_BUCKET}/${S3_PREFIX}/files"
            RESTIC_PASSWORD: ${ENCRYPTION_PASSWORD}
            TZ: CET

    restore:
        image: mazzolino/restic
        hostname: docker
        profiles: ["restore"]
        environment:
            RUN_ON_STARTUP: "true"
            AWS_ACCESS_KEY_ID: "${S3_ACCESS_KEY_ID}"
            AWS_SECRET_ACCESS_KEY: "${S3_SECRET_ACCESS_KEY}"
            RESTIC_REPOSITORY: "s3:${S3_ENDPOINT}/${S3_BUCKET}/${S3_PREFIX}/files"
            RESTIC_PASSWORD: ${ENCRYPTION_PASSWORD}
            TZ: CET
        volumes:
            - "plex-config:/data"
        entrypoint: bash -c "apk add jq && sleep infinity"

volumes:
    plex-config:
